export { lotsConfig } from './lots.config'
export { coproprietairesConfig } from './coproprietaires.config'
export { soldesConfig } from './soldes.config'
export { paiementsConfig } from './paiements.config'
export { prestatairesConfig } from './prestataires.config'
